name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build --build-arg PORT_ARG=3001 -t ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME} .

      - name: Push image
        run: docker push ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}